### ISSUE TITLE
FreeListSpace在初始化的时候被设置了固定大小，使用修改heap已分配的大小貌似并不能影响到FreeListSpace的分配

### ISSUE THREAD

**Issue by leeaction** [TestPlanB/mooner#3]
使用此方法，依然会在heap内存达到512的时候发生OOM

**Comment by TestPlanB** [comment]
感谢提问，挺好的一个问题。FreeListSpace本身被设定的大小，这个是我们没办法更改的。但是我们能让OOM计算时的堆内存减去这部分内存，达到一个增量。因为512它针对的是总内存超限与单个内存超限，如果你想的是只在FreeListSpace中分配对象，那么的确没办法超过512。但是实际上，ART并不只在FreeListSpace中分配内存，其他还有很多空间。逻辑上是能够突破512M的，可以运行一下demo跑一下看看内存数据

**Comment by TestPlanB** [comment]
demo中，我划分了几个分配按钮，小对象它会被分配在regionspace中，大对象会被分配在LOS中，也是FreeListSpace，可以看看视频点击几下

**Comment by CaichaoGitHub** [comment]
> demo中，我划分了几个分配按钮，小对象它会被分配在regionspace中，大对象会被分配在LOS中，也是FreeListSpace，可以看看视频点击几下

我尝试在发生OOM 的时候，回调java 层，释放掉一些java对象，貌似并不能触发 GC ，回收内存，最后还是嘣了
