### ISSUE TITLE
OOM保护成功后，在AS中强制GC回收内存，直接崩了

### ISSUE THREAD

**Issue by CaichaoGitHub** [TestPlanB/mooner#4]
OOM保护成功后，我在java层释放了对象引用
![image](https://github.com/TestPlanB/mooner/assets/12059897/fc172dd2-9c7c-45dd-b1fc-583cb9dcb950)

，然后在AS中强制GC回收内存，直接崩了

**Comment by TestPlanB** [comment]
好的，方便留意下机型和版本号嘛，我这边复现一下

**Comment by CaichaoGitHub** [comment]
小米9se ,miui 12.5.4 , 我定位了一下，应该是 回收的时候，heap 中的 num_bytes_allocated_ 减成了负数；堆 修改哪里的逻辑应该有些问题

**Comment by TestPlanB** [comment]
感谢支持！问题已经定位，后续会修复
